# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - shell: bash
        run: curl -o settings.xml https://raw.githubusercontent.com/santosh265/maven-settings/main/settings.xml
      - name: Build with Maven
        run: mvn -s settings.xml -X -Dnexus=${{ secrets.NEXUS }} deploy -Dusername=${{ secrets.ANYPOINT_USR }} -Dpassword=${{ secrets.ANYPOINT_PSW }} -DapplicationName=Zsguychsv-GVDsw -DworkerType=Micro -Dworkers=1 -Dregion=us-west-2 -Denvironment=Sandbox
